name: 📚 書籍企画提案
description: 新しい書籍の企画提案や既存書籍の改善提案
title: "[書籍企画] "
labels: ["book-proposal", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📚 書籍企画提案
        IT Engineer Knowledge Architectureプロジェクトに新しい書籍企画や改善提案をお寄せください。

  - type: dropdown
    id: proposal-type
    attributes:
      label: 提案タイプ
      description: どのような提案ですか？
      options:
        - 新規書籍企画
        - 既存書籍の改善提案
        - 学習パスの追加・修正
        - その他
    validations:
      required: true

  - type: input
    id: book-title
    attributes:
      label: 書籍タイトル
      description: 提案する書籍のタイトル
      placeholder: 例：『Kubernetes運用実践ガイド』
    validations:
      required: true

  - type: dropdown
    id: target-level
    attributes:
      label: 対象レベル
      description: 想定する読者のレベル
      options:
        - 初級者（経験0-2年）
        - 中級者（経験3-5年）
        - 上級者（経験6年以上）
        - エキスパート（シニア・責任者）
        - 全レベル
    validations:
      required: true

  - type: dropdown
    id: technical-area
    attributes:
      label: 技術領域
      description: 主な技術領域
      options:
        - インフラ・システム運用
        - クラウドアーキテクチャ
        - セキュリティ
        - 監視・運用自動化
        - DevOps・SRE
        - コンテナ・オーケストレーション
        - ネットワーク
        - データベース
        - AI・機械学習
        - ソフトスキル・マネジメント
        - その他
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この書籍の重要度
      options:
        - 高（実務で必須）
        - 中（スキル向上に有効）
        - 低（将来的な価値）
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 書籍概要
      description: 書籍の概要・目的・特徴
      placeholder: |
        この書籍の目的、対象読者、主な内容について説明してください。
        
        例：
        - 目的：Kubernetesの本格運用に必要な実践的知識の提供
        - 特徴：本番環境での運用経験に基づく実践的な内容
        - 既存書籍との差別化：理論よりも運用・トラブルシューティングに重点
    validations:
      required: true

  - type: textarea
    id: target-readers
    attributes:
      label: 対象読者
      description: 想定する読者の詳細
      placeholder: |
        - Kubernetesの基本概念を理解している開発者・インフラエンジニア
        - 本番環境でのKubernetes導入を検討している企業の技術者
        - コンテナオーケストレーションの実践的スキルを身につけたいエンジニア

  - type: textarea
    id: table-of-contents
    attributes:
      label: 想定目次
      description: 章立て・主要トピック
      placeholder: |
        第1章：Kubernetes運用の基本原則
        第2章：クラスタ設計・構築
        第3章：アプリケーションデプロイメント戦略
        第4章：監視・ログ管理
        第5章：トラブルシューティング
        第6章：セキュリティ・ガバナンス
        付録：運用チェックリスト・ツール集

  - type: textarea
    id: differentiation
    attributes:
      label: 既存書籍との差別化
      description: 既存の類書との違い・優位性
      placeholder: |
        - 既存のKubernetes入門書：基本概念中心 → 本書：運用実践に特化
        - 一般的な技術書：理論重視 → 本書：実際の運用経験・失敗例を含む実践重視
        - 海外書籍：文化・環境の違い → 本書：日本企業の運用実態に即した内容

  - type: input
    id: estimated-pages
    attributes:
      label: 想定ページ数
      placeholder: 例：250-300ページ
    validations:
      required: false

  - type: input
    id: estimated-duration
    attributes:
      label: 想定学習期間
      placeholder: 例：6-8週間
    validations:
      required: false

  - type: textarea
    id: prerequisites
    attributes:
      label: 前提知識
      description: 読者に必要な前提知識・スキル
      placeholder: |
        - Linux基本操作
        - Docker基礎知識
        - ネットワーク基礎
        - YAML記法の理解

  - type: textarea
    id: practical-value
    attributes:
      label: 実務での価値・活用場面
      description: この書籍で学んだ内容がどのような実務で活用できるか
      placeholder: |
        - Kubernetesクラスタの本格運用開始
        - マイクロサービス基盤の構築・運用
        - CI/CDパイプラインの改善
        - インフラコスト最適化
        - 障害対応・復旧作業の効率化

  - type: textarea
    id: related-books
    attributes:
      label: 関連書籍・学習パス
      description: この書籍と組み合わせて学習すべき他の書籍
      placeholder: |
        前提：
        - linux-infra-textbook
        - podman-book
        
        組み合わせ：
        - インフラ監視・運用自動化実践ガイド
        - 実践的セキュリティインフラ構築
        
        発展：
        - エンタープライズクラウドアーキテクチャ設計・運用

  - type: textarea
    id: additional-info
    attributes:
      label: その他・補足情報
      description: その他の提案・要望・参考情報
      placeholder: |
        - 想定する執筆者の専門性
        - 参考にすべき技術・事例
        - 特別な要望・制約事項
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: 確認事項
      description: 以下の内容を確認してください
      options:
        - label: この提案は実務での需要に基づいている
          required: true
        - label: 既存の13冊 + 計画7冊との重複を確認済み
          required: true
        - label: 対象読者・レベルが明確に定義されている
          required: true